services:
  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - ollama
    networks:
      - app-net

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    environment:
      - OLLAMA_MODELS=/root/.ollama/models
    networks:
      - app-net
    restart: unless-stopped
    entrypoint: >
      /bin/sh -c " ollama serve &  sleep 5 &&  ollama pull llama3.2 && tail -f /dev/null "

volumes:
  ollama_data:


networks:
  app-net:
    driver: bridge
